% Produced by CVXGEN, 2017-07-06 05:35:12 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
Q = params.Q;
b = params.b;
c = params.c;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable x(12, 1);

  minimize(quad_form(x, Q) + c'*x);
  subject to
    A*x == b;
    50 <= x(1);
    50 <= x(2);
    50 <= x(3);
    50 <= x(4);
    50 <= x(5);
    50 <= x(6);
    50 <= x(7);
    50 <= x(8);
    x(1) <= 10000;
    x(2) <= 10000;
    x(3) <= 10000;
    x(4) <= 10000;
    x(5) <= 10000;
    x(6) <= 10000;
    x(7) <= 10000;
    x(8) <= 10000;
    -0.01 <= x(9);
    -0.01 <= x(10);
    -0.01 <= x(11);
    -0.01 <= x(12);
    x(9) <= 0.01;
    x(10) <= 0.01;
    x(11) <= 0.01;
    x(12) <= 0.01;
cvx_end
vars.x = x;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
