# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cabledrivenparallerobot.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CableDrivenParalleRobot(object):
    def setupUi(self, CableDrivenParalleRobot):
        CableDrivenParalleRobot.setObjectName("CableDrivenParalleRobot")
        CableDrivenParalleRobot.setEnabled(True)
        CableDrivenParalleRobot.resize(904, 682)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CableDrivenParalleRobot.sizePolicy().hasHeightForWidth())
        CableDrivenParalleRobot.setSizePolicy(sizePolicy)
        CableDrivenParalleRobot.setMinimumSize(QtCore.QSize(904, 682))
        CableDrivenParalleRobot.setMaximumSize(QtCore.QSize(904, 682))
        self.centralWidget = QtWidgets.QWidget(CableDrivenParalleRobot)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(730, 536, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 600, 131, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(470, 10, 131, 16))
        self.label_16.setObjectName("label_16")
        self.layoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 359, 318))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.anchorpoint1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint1.setObjectName("anchorpoint1")
        self.gridLayout.addWidget(self.anchorpoint1, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.anchorpoint2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint2.setObjectName("anchorpoint2")
        self.gridLayout.addWidget(self.anchorpoint2, 2, 1, 1, 1)
        self.exitpoint2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint2.setObjectName("exitpoint2")
        self.gridLayout.addWidget(self.exitpoint2, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.anchorpoint3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint3.setObjectName("anchorpoint3")
        self.gridLayout.addWidget(self.anchorpoint3, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.exitpoint3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint3.setObjectName("exitpoint3")
        self.gridLayout.addWidget(self.exitpoint3, 3, 2, 1, 1)
        self.exitpoint1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint1.setObjectName("exitpoint1")
        self.gridLayout.addWidget(self.exitpoint1, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.anchorpoint4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint4.setObjectName("anchorpoint4")
        self.gridLayout_2.addWidget(self.anchorpoint4, 1, 1, 1, 1)
        self.exitpoint4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint4.setObjectName("exitpoint4")
        self.gridLayout_2.addWidget(self.exitpoint4, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.anchorpoint5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint5.setObjectName("anchorpoint5")
        self.gridLayout_2.addWidget(self.anchorpoint5, 2, 1, 1, 1)
        self.exitpoint5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint5.setObjectName("exitpoint5")
        self.gridLayout_2.addWidget(self.exitpoint5, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.anchorpoint6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint6.setObjectName("anchorpoint6")
        self.gridLayout_2.addWidget(self.anchorpoint6, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.anchorpoint7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint7.setObjectName("anchorpoint7")
        self.gridLayout_2.addWidget(self.anchorpoint7, 4, 1, 1, 1)
        self.exitpoint7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint7.setObjectName("exitpoint7")
        self.gridLayout_2.addWidget(self.exitpoint7, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.exitpoint8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint8.setObjectName("exitpoint8")
        self.gridLayout_2.addWidget(self.exitpoint8, 5, 2, 1, 1)
        self.anchorpoint8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.anchorpoint8.setObjectName("anchorpoint8")
        self.gridLayout_2.addWidget(self.anchorpoint8, 5, 1, 1, 1)
        self.exitpoint6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.exitpoint6.setObjectName("exitpoint6")
        self.gridLayout_2.addWidget(self.exitpoint6, 3, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(470, 30, 189, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.CableMass = QtWidgets.QLineEdit(self.layoutWidget1)
        self.CableMass.setObjectName("CableMass")
        self.horizontalLayout_3.addWidget(self.CableMass)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(470, 60, 200, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.CableRadius = QtWidgets.QLineEdit(self.layoutWidget2)
        self.CableRadius.setObjectName("CableRadius")
        self.horizontalLayout_4.addWidget(self.CableRadius)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 570, 131, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(30, 470, 121, 17))
        self.label_19.setObjectName("label_19")
        self.label_29 = QtWidgets.QLabel(self.centralWidget)
        self.label_29.setGeometry(QtCore.QRect(60, 0, 191, 17))
        self.label_29.setObjectName("label_29")
        self.CableMass_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.CableMass_3.setGeometry(QtCore.QRect(575, 756, 81, 27))
        self.CableMass_3.setObjectName("CableMass_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 490, 332, 118))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 2, 1, 1)
        self.Inertialyy = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialyy.setObjectName("Inertialyy")
        self.gridLayout_3.addWidget(self.Inertialyy, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 2, 0, 1, 1)
        self.Inertialyz = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialyz.setObjectName("Inertialyz")
        self.gridLayout_3.addWidget(self.Inertialyz, 1, 5, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 2, 2, 1, 1)
        self.Inertialyz_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialyz_2.setObjectName("Inertialyz_2")
        self.gridLayout_3.addWidget(self.Inertialyz_2, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 2, 4, 1, 1)
        self.Inertialxy = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialxy.setObjectName("Inertialxy")
        self.gridLayout_3.addWidget(self.Inertialxy, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.Inertialxx = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialxx.setObjectName("Inertialxx")
        self.gridLayout_3.addWidget(self.Inertialxx, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.Inertialxz = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialxz.setObjectName("Inertialxz")
        self.gridLayout_3.addWidget(self.Inertialxz, 0, 5, 1, 1)
        self.Inertialxy_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialxy_2.setObjectName("Inertialxy_2")
        self.gridLayout_3.addWidget(self.Inertialxy_2, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 4, 1, 1)
        self.Inertialxz_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialxz_2.setObjectName("Inertialxz_2")
        self.gridLayout_3.addWidget(self.Inertialxz_2, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.Inertialzz = QtWidgets.QLineEdit(self.layoutWidget3)
        self.Inertialzz.setObjectName("Inertialzz")
        self.gridLayout_3.addWidget(self.Inertialzz, 2, 5, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 370, 306, 89))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.endeffMass = QtWidgets.QLineEdit(self.layoutWidget4)
        self.endeffMass.setObjectName("endeffMass")
        self.horizontalLayout.addWidget(self.endeffMass)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.endEffShape_2 = QtWidgets.QComboBox(self.layoutWidget4)
        self.endEffShape_2.setObjectName("endEffShape_2")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.endEffShape_2.addItem("")
        self.gridLayout_4.addWidget(self.endEffShape_2, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.endEffShape = QtWidgets.QComboBox(self.layoutWidget4)
        self.endEffShape.setObjectName("endEffShape")
        self.endEffShape.addItem("")
        self.endEffShape.addItem("")
        self.horizontalLayout_2.addWidget(self.endEffShape)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(350, 370, 252, 85))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 0, 0, 1, 2)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 2, 0, 1, 1)
        self.endeffRPY = QtWidgets.QLineEdit(self.layoutWidget5)
        self.endeffRPY.setObjectName("endeffRPY")
        self.gridLayout_6.addWidget(self.endeffRPY, 2, 1, 1, 1)
        self.endeffPosition = QtWidgets.QLineEdit(self.layoutWidget5)
        self.endeffPosition.setObjectName("endeffPosition")
        self.gridLayout_6.addWidget(self.endeffPosition, 1, 1, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(420, 140, 332, 159))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.endEffShape_5 = QtWidgets.QComboBox(self.layoutWidget6)
        self.endEffShape_5.setObjectName("endEffShape_5")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.endEffShape_5.addItem("")
        self.gridLayout_7.addWidget(self.endEffShape_5, 2, 2, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.label_40)
        self.endEffShape_6 = QtWidgets.QComboBox(self.layoutWidget6)
        self.endEffShape_6.setObjectName("endEffShape_6")
        self.endEffShape_6.addItem("")
        self.horizontalLayout_8.addWidget(self.endEffShape_6)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_7.addWidget(self.label_39)
        self.endeffMass_3 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.endeffMass_3.setObjectName("endeffMass_3")
        self.horizontalLayout_7.addWidget(self.endeffMass_3)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 1, 0, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 2, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lowerframe = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lowerframe.setObjectName("lowerframe")
        self.gridLayout_8.addWidget(self.lowerframe, 1, 1, 1, 1)
        self.upperframe = QtWidgets.QLineEdit(self.layoutWidget6)
        self.upperframe.setObjectName("upperframe")
        self.gridLayout_8.addWidget(self.upperframe, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.centralWidget)
        self.label_55.setGeometry(QtCore.QRect(850, 1060, 41, 27))
        self.label_55.setObjectName("label_55")
        self.layoutWidget7 = QtWidgets.QWidget(self.centralWidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(370, 480, 311, 91))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 1, 5, 1, 1)
        self.fmax = QtWidgets.QLineEdit(self.layoutWidget7)
        self.fmax.setObjectName("fmax")
        self.gridLayout_5.addWidget(self.fmax, 1, 2, 1, 3)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 2, 3, 1, 1)
        self.P = QtWidgets.QLineEdit(self.layoutWidget7)
        self.P.setObjectName("P")
        self.gridLayout_5.addWidget(self.P, 2, 1, 1, 2)
        self.fmin = QtWidgets.QLineEdit(self.layoutWidget7)
        self.fmin.setObjectName("fmin")
        self.gridLayout_5.addWidget(self.fmin, 1, 6, 1, 2)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 2, 0, 1, 1)
        self.d = QtWidgets.QLineEdit(self.layoutWidget7)
        self.d.setObjectName("d")
        self.gridLayout_5.addWidget(self.d, 2, 7, 1, 1)
        self.I = QtWidgets.QLineEdit(self.layoutWidget7)
        self.I.setObjectName("I")
        self.gridLayout_5.addWidget(self.I, 2, 4, 1, 2)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 2, 6, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 0, 2, 1, 6)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_16.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton_3.raise_()
        self.label_19.raise_()
        self.label_29.raise_()
        self.CableMass_3.raise_()
        self.label_55.raise_()
        CableDrivenParalleRobot.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(CableDrivenParalleRobot)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 904, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuCDPR_Parameters = QtWidgets.QMenu(self.menuBar)
        self.menuCDPR_Parameters.setObjectName("menuCDPR_Parameters")
        self.menuImport = QtWidgets.QMenu(self.menuCDPR_Parameters)
        self.menuImport.setObjectName("menuImport")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        CableDrivenParalleRobot.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(CableDrivenParalleRobot)
        self.mainToolBar.setObjectName("mainToolBar")
        CableDrivenParalleRobot.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(CableDrivenParalleRobot)
        self.statusBar.setObjectName("statusBar")
        CableDrivenParalleRobot.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(CableDrivenParalleRobot)
        self.toolBar.setObjectName("toolBar")
        CableDrivenParalleRobot.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Window = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionClose = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionClose.setObjectName("actionClose")
        self.actionFile = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionFile.setObjectName("actionFile")
        self.actionRobot = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionRobot.setObjectName("actionRobot")
        self.actionCopy = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionPaste.setObjectName("actionPaste")
        self.actionClear = QtWidgets.QAction(CableDrivenParalleRobot)
        self.actionClear.setObjectName("actionClear")
        self.menuImport.addAction(self.actionFile)
        self.menuImport.addAction(self.actionRobot)
        self.menuCDPR_Parameters.addAction(self.actionNew_Window)
        self.menuCDPR_Parameters.addAction(self.actionClose)
        self.menuCDPR_Parameters.addAction(self.menuImport.menuAction())
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionClear)
        self.menuBar.addAction(self.menuCDPR_Parameters.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(CableDrivenParalleRobot)
        self.pushButton.clicked.connect(CableDrivenParalleRobot.close)
        QtCore.QMetaObject.connectSlotsByName(CableDrivenParalleRobot)

    def retranslateUi(self, CableDrivenParalleRobot):
        _translate = QtCore.QCoreApplication.translate
        CableDrivenParalleRobot.setWindowTitle(_translate("CableDrivenParalleRobot", "CableDrivenParalleRobot"))
        self.pushButton.setText(_translate("CableDrivenParalleRobot", "Close"))
        self.pushButton_2.setText(_translate("CableDrivenParalleRobot", "Save Parameters"))
        self.label_16.setText(_translate("CableDrivenParalleRobot", "Cable Paramters"))
        self.label.setText(_translate("CableDrivenParalleRobot", "Anchor Points"))
        self.label_2.setText(_translate("CableDrivenParalleRobot", "Exit  Points"))
        self.label_3.setText(_translate("CableDrivenParalleRobot", "Cable 1"))
        self.label_4.setText(_translate("CableDrivenParalleRobot", "Cable 2"))
        self.label_5.setText(_translate("CableDrivenParalleRobot", "Cable 3"))
        self.label_12.setText(_translate("CableDrivenParalleRobot", "Cable"))
        self.label_7.setText(_translate("CableDrivenParalleRobot", "Cable 4"))
        self.label_8.setText(_translate("CableDrivenParalleRobot", "Cable 5"))
        self.label_9.setText(_translate("CableDrivenParalleRobot", "Cable 6"))
        self.label_10.setText(_translate("CableDrivenParalleRobot", "Cable 7"))
        self.label_11.setText(_translate("CableDrivenParalleRobot", "Cable 8"))
        self.label_17.setText(_translate("CableDrivenParalleRobot", "Mass"))
        self.label_18.setText(_translate("CableDrivenParalleRobot", "Radius"))
        self.pushButton_3.setText(_translate("CableDrivenParalleRobot", "Load Parameters"))
        self.label_19.setText(_translate("CableDrivenParalleRobot", "Inertial Paramters"))
        self.label_29.setText(_translate("CableDrivenParalleRobot", "Enter Co-ordinates as  X,Y,Z"))
        self.label_24.setText(_translate("CableDrivenParalleRobot", "Iyy"))
        self.label_26.setText(_translate("CableDrivenParalleRobot", "Ixz"))
        self.label_27.setText(_translate("CableDrivenParalleRobot", "Iyz"))
        self.label_25.setText(_translate("CableDrivenParalleRobot", "Izz"))
        self.label_6.setText(_translate("CableDrivenParalleRobot", "Ixx"))
        self.label_20.setText(_translate("CableDrivenParalleRobot", "Ixy"))
        self.label_21.setText(_translate("CableDrivenParalleRobot", "Ixz"))
        self.label_22.setText(_translate("CableDrivenParalleRobot", "Iyz"))
        self.label_23.setText(_translate("CableDrivenParalleRobot", "Ixy"))
        self.label_28.setText(_translate("CableDrivenParalleRobot", "Color"))
        self.label_13.setText(_translate("CableDrivenParalleRobot", "Mass"))
        self.endEffShape_2.setItemText(0, _translate("CableDrivenParalleRobot", "Black"))
        self.endEffShape_2.setItemText(1, _translate("CableDrivenParalleRobot", "Blue"))
        self.endEffShape_2.setItemText(2, _translate("CableDrivenParalleRobot", "Grey"))
        self.endEffShape_2.setItemText(3, _translate("CableDrivenParalleRobot", "Yellow"))
        self.endEffShape_2.setItemText(4, _translate("CableDrivenParalleRobot", "Green"))
        self.endEffShape_2.setItemText(5, _translate("CableDrivenParalleRobot", "White"))
        self.endEffShape_2.setItemText(6, _translate("CableDrivenParalleRobot", "Orange"))
        self.endEffShape_2.setItemText(7, _translate("CableDrivenParalleRobot", "Red"))
        self.label_14.setText(_translate("CableDrivenParalleRobot", "Shape"))
        self.endEffShape.setItemText(0, _translate("CableDrivenParalleRobot", "Sphere"))
        self.endEffShape.setItemText(1, _translate("CableDrivenParalleRobot", "Box"))
        self.label_15.setText(_translate("CableDrivenParalleRobot", "End-Effector Paramters"))
        self.label_31.setText(_translate("CableDrivenParalleRobot", "Initial End-Effector Pose"))
        self.label_37.setText(_translate("CableDrivenParalleRobot", "Position X,Y,Z"))
        self.label_30.setText(_translate("CableDrivenParalleRobot", "Orientation R,P,Y"))
        self.endEffShape_5.setItemText(0, _translate("CableDrivenParalleRobot", "Black"))
        self.endEffShape_5.setItemText(1, _translate("CableDrivenParalleRobot", "Blue"))
        self.endEffShape_5.setItemText(2, _translate("CableDrivenParalleRobot", "Grey"))
        self.endEffShape_5.setItemText(3, _translate("CableDrivenParalleRobot", "Yellow"))
        self.endEffShape_5.setItemText(4, _translate("CableDrivenParalleRobot", "Green"))
        self.endEffShape_5.setItemText(5, _translate("CableDrivenParalleRobot", "White"))
        self.endEffShape_5.setItemText(6, _translate("CableDrivenParalleRobot", "Orange"))
        self.endEffShape_5.setItemText(7, _translate("CableDrivenParalleRobot", "Red"))
        self.label_40.setText(_translate("CableDrivenParalleRobot", "Shape"))
        self.endEffShape_6.setItemText(0, _translate("CableDrivenParalleRobot", "Box"))
        self.label_39.setText(_translate("CableDrivenParalleRobot", "Mass"))
        self.label_38.setText(_translate("CableDrivenParalleRobot", "Color"))
        self.label_41.setText(_translate("CableDrivenParalleRobot", "Bounding Frame Paramters"))
        self.label_43.setText(_translate("CableDrivenParalleRobot", "Lowest Edge co-ordinate"))
        self.label_44.setText(_translate("CableDrivenParalleRobot", "Uppermost Edge co-ordinate"))
        self.label_55.setText(_translate("CableDrivenParalleRobot", "Fmin"))
        self.label_34.setText(_translate("CableDrivenParalleRobot", "Fmax"))
        self.label_35.setText(_translate("CableDrivenParalleRobot", "Fmin"))
        self.label_54.setText(_translate("CableDrivenParalleRobot", "I"))
        self.label_36.setText(_translate("CableDrivenParalleRobot", "P"))
        self.label_33.setText(_translate("CableDrivenParalleRobot", "D"))
        self.label_32.setText(_translate("CableDrivenParalleRobot", "Control Paramters"))
        self.menuCDPR_Parameters.setTitle(_translate("CableDrivenParalleRobot", "File"))
        self.menuImport.setTitle(_translate("CableDrivenParalleRobot", "Import"))
        self.menuEdit.setTitle(_translate("CableDrivenParalleRobot", "Edit"))
        self.toolBar.setWindowTitle(_translate("CableDrivenParalleRobot", "toolBar"))
        self.actionNew_Window.setText(_translate("CableDrivenParalleRobot", "Open"))
        self.actionClose.setText(_translate("CableDrivenParalleRobot", "Close"))
        self.actionFile.setText(_translate("CableDrivenParalleRobot", "File"))
        self.actionRobot.setText(_translate("CableDrivenParalleRobot", "Robot"))
        self.actionCopy.setText(_translate("CableDrivenParalleRobot", "Copy"))
        self.actionPaste.setText(_translate("CableDrivenParalleRobot", "Paste"))
        self.actionClear.setText(_translate("CableDrivenParalleRobot", "Clear"))

