% Produced by CVXGEN, 2017-06-19 05:31:22 -0400.
% CVXGEN is Copyright (C) 2006-2012 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2012 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
Q = params.Q;
b = params.b;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable x(8, 1);

  minimize(quad_form(x, Q));
  subject to
    A*x == b;
    50 <= x;
    x <= 10000;
cvx_end
vars.x = x;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
