# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cabledrivenparallerobot.ui'
#
# Created: Tue May 24 14:14:01 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from saveparam import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CableDrivenParalleRobot(object):
    def setupUi(self, CableDrivenParalleRobot):
        CableDrivenParalleRobot.setObjectName(_fromUtf8("CableDrivenParalleRobot"))
        CableDrivenParalleRobot.resize(904, 537)
        self.centralWidget = QtGui.QWidget(CableDrivenParalleRobot)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(730, 346, 91, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 410, 131, 21))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_15 = QtGui.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(30, 350, 161, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(470, 10, 131, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 359, 318))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.anchorpoint1 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint1.setObjectName(_fromUtf8("anchorpoint1"))
        self.gridLayout.addWidget(self.anchorpoint1, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.anchorpoint2 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint2.setObjectName(_fromUtf8("anchorpoint2"))
        self.gridLayout.addWidget(self.anchorpoint2, 2, 1, 1, 1)
        self.exitpoint2 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint2.setObjectName(_fromUtf8("exitpoint2"))
        self.gridLayout.addWidget(self.exitpoint2, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.anchorpoint3 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint3.setObjectName(_fromUtf8("anchorpoint3"))
        self.gridLayout.addWidget(self.anchorpoint3, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.exitpoint3 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint3.setObjectName(_fromUtf8("exitpoint3"))
        self.gridLayout.addWidget(self.exitpoint3, 3, 2, 1, 1)
        self.exitpoint1 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint1.setObjectName(_fromUtf8("exitpoint1"))
        self.gridLayout.addWidget(self.exitpoint1, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.anchorpoint4 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint4.setObjectName(_fromUtf8("anchorpoint4"))
        self.gridLayout_2.addWidget(self.anchorpoint4, 1, 1, 1, 1)
        self.exitpoint4 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint4.setObjectName(_fromUtf8("exitpoint4"))
        self.gridLayout_2.addWidget(self.exitpoint4, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.anchorpoint5 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint5.setObjectName(_fromUtf8("anchorpoint5"))
        self.gridLayout_2.addWidget(self.anchorpoint5, 2, 1, 1, 1)
        self.exitpoint5 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint5.setObjectName(_fromUtf8("exitpoint5"))
        self.gridLayout_2.addWidget(self.exitpoint5, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.anchorpoint6 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint6.setObjectName(_fromUtf8("anchorpoint6"))
        self.gridLayout_2.addWidget(self.anchorpoint6, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.anchorpoint7 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint7.setObjectName(_fromUtf8("anchorpoint7"))
        self.gridLayout_2.addWidget(self.anchorpoint7, 4, 1, 1, 1)
        self.exitpoint7 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint7.setObjectName(_fromUtf8("exitpoint7"))
        self.gridLayout_2.addWidget(self.exitpoint7, 4, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.exitpoint8 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint8.setObjectName(_fromUtf8("exitpoint8"))
        self.gridLayout_2.addWidget(self.exitpoint8, 5, 2, 1, 1)
        self.anchorpoint8 = QtGui.QLineEdit(self.layoutWidget)
        self.anchorpoint8.setObjectName(_fromUtf8("anchorpoint8"))
        self.gridLayout_2.addWidget(self.anchorpoint8, 5, 1, 1, 1)
        self.exitpoint6 = QtGui.QLineEdit(self.layoutWidget)
        self.exitpoint6.setObjectName(_fromUtf8("exitpoint6"))
        self.gridLayout_2.addWidget(self.exitpoint6, 3, 2, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 380, 189, 29))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.endeffMass = QtGui.QLineEdit(self.layoutWidget1)
        self.endeffMass.setObjectName(_fromUtf8("endeffMass"))
        self.horizontalLayout.addWidget(self.endeffMass)
        self.layoutWidget2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 410, 127, 29))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_14 = QtGui.QLabel(self.layoutWidget2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        self.endEffShape = QtGui.QComboBox(self.layoutWidget2)
        self.endEffShape.setObjectName(_fromUtf8("endEffShape"))
        self.endEffShape.addItem(_fromUtf8(""))
        self.endEffShape.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.endEffShape)
        self.layoutWidget3 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(470, 30, 189, 29))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_3.addWidget(self.label_17)
        self.CableMass = QtGui.QLineEdit(self.layoutWidget3)
        self.CableMass.setObjectName(_fromUtf8("CableMass"))
        self.horizontalLayout_3.addWidget(self.CableMass)
        self.layoutWidget4 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(470, 60, 200, 29))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_18 = QtGui.QLabel(self.layoutWidget4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_4.addWidget(self.label_18)
        self.CableRadius = QtGui.QLineEdit(self.layoutWidget4)
        self.CableRadius.setObjectName(_fromUtf8("CableRadius"))
        self.horizontalLayout_4.addWidget(self.CableRadius)
        self.pushButton_3 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(710, 380, 131, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        CableDrivenParalleRobot.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(CableDrivenParalleRobot)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 904, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuCDPR_Parameters = QtGui.QMenu(self.menuBar)
        self.menuCDPR_Parameters.setObjectName(_fromUtf8("menuCDPR_Parameters"))
        self.menuImport = QtGui.QMenu(self.menuCDPR_Parameters)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        CableDrivenParalleRobot.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(CableDrivenParalleRobot)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        CableDrivenParalleRobot.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(CableDrivenParalleRobot)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        CableDrivenParalleRobot.setStatusBar(self.statusBar)
        self.actionNew_Window = QtGui.QAction(CableDrivenParalleRobot)
        self.actionNew_Window.setObjectName(_fromUtf8("actionNew_Window"))
        self.actionClose = QtGui.QAction(CableDrivenParalleRobot)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionFile = QtGui.QAction(CableDrivenParalleRobot)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionRobot = QtGui.QAction(CableDrivenParalleRobot)
        self.actionRobot.setObjectName(_fromUtf8("actionRobot"))
        self.actionCopy = QtGui.QAction(CableDrivenParalleRobot)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(CableDrivenParalleRobot)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionClear = QtGui.QAction(CableDrivenParalleRobot)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.menuImport.addAction(self.actionFile)
        self.menuImport.addAction(self.actionRobot)
        self.menuCDPR_Parameters.addAction(self.actionNew_Window)
        self.menuCDPR_Parameters.addAction(self.actionClose)
        self.menuCDPR_Parameters.addAction(self.menuImport.menuAction())
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionClear)
        self.menuBar.addAction(self.menuCDPR_Parameters.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(CableDrivenParalleRobot)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), CableDrivenParalleRobot.close)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pSaveParameter)
        QtCore.QMetaObject.connectSlotsByName(CableDrivenParalleRobot)

    def retranslateUi(self, CableDrivenParalleRobot):
        CableDrivenParalleRobot.setWindowTitle(_translate("CableDrivenParalleRobot", "CableDrivenParalleRobot", None))
        self.pushButton.setText(_translate("CableDrivenParalleRobot", "Close", None))
        self.pushButton_2.setText(_translate("CableDrivenParalleRobot", "Save Parameters", None))
        self.label_15.setText(_translate("CableDrivenParalleRobot", "End-Effector Paramters", None))
        self.label_16.setText(_translate("CableDrivenParalleRobot", "Cable Paramters", None))
        self.label.setText(_translate("CableDrivenParalleRobot", "Anchor Points", None))
        self.label_2.setText(_translate("CableDrivenParalleRobot", "Exit  Points", None))
        self.label_3.setText(_translate("CableDrivenParalleRobot", "Cable 1", None))
        self.label_4.setText(_translate("CableDrivenParalleRobot", "Cable 2", None))
        self.label_5.setText(_translate("CableDrivenParalleRobot", "Cable 3", None))
        self.label_12.setText(_translate("CableDrivenParalleRobot", "Cable", None))
        self.label_7.setText(_translate("CableDrivenParalleRobot", "Cable 4", None))
        self.label_8.setText(_translate("CableDrivenParalleRobot", "Cable 5", None))
        self.label_9.setText(_translate("CableDrivenParalleRobot", "Cable 6", None))
        self.label_10.setText(_translate("CableDrivenParalleRobot", "Cable 7", None))
        self.label_11.setText(_translate("CableDrivenParalleRobot", "Cable 8", None))
        self.label_13.setText(_translate("CableDrivenParalleRobot", "Mass", None))
        self.label_14.setText(_translate("CableDrivenParalleRobot", "Shape", None))
        self.endEffShape.setItemText(0, _translate("CableDrivenParalleRobot", "Sphere", None))
        self.endEffShape.setItemText(1, _translate("CableDrivenParalleRobot", "Box", None))
        self.label_17.setText(_translate("CableDrivenParalleRobot", "Mass", None))
        self.label_18.setText(_translate("CableDrivenParalleRobot", "Radius", None))
        self.pushButton_3.setText(_translate("CableDrivenParalleRobot", "Load Parameters", None))
        self.menuCDPR_Parameters.setTitle(_translate("CableDrivenParalleRobot", "File", None))
        self.menuImport.setTitle(_translate("CableDrivenParalleRobot", "Import", None))
        self.menuEdit.setTitle(_translate("CableDrivenParalleRobot", "Edit", None))
        self.actionNew_Window.setText(_translate("CableDrivenParalleRobot", "Open", None))
        self.actionClose.setText(_translate("CableDrivenParalleRobot", "Close", None))
        self.actionFile.setText(_translate("CableDrivenParalleRobot", "File", None))
        self.actionRobot.setText(_translate("CableDrivenParalleRobot", "Robot", None))
        self.actionCopy.setText(_translate("CableDrivenParalleRobot", "Copy", None))
        self.actionPaste.setText(_translate("CableDrivenParalleRobot", "Paste", None))
        self.actionClear.setText(_translate("CableDrivenParalleRobot", "Clear", None))

    def pSaveParameter(self):
        SaveParameter(self)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CableDrivenParalleRobot = QtGui.QMainWindow()
    ui = Ui_CableDrivenParalleRobot()
    ui.setupUi(CableDrivenParalleRobot)
    CableDrivenParalleRobot.show()
    app.exec_()
    #ui.pushButton_2.clicked()
    #sys.exit(app.exec_())


